-- Clean up dependent tables first (in correct order)
DELETE FROM Barangay;
DBCC CHECKIDENT ('Barangay', RESEED, 0);

DELETE FROM Municipality;
DBCC CHECKIDENT ('Municipality', RESEED, 0);

DELETE FROM Province;
DBCC CHECKIDENT ('Province', RESEED, 0);

-- Enable identity insert
SET IDENTITY_INSERT Province ON;

-- Insert Provinces
INSERT INTO Province (ProvinceId, ProvinceName) VALUES
    (1, 'Abra'),
    (2, 'Agusan del Norte'),
    (3, 'Agusan del Sur'),
    (4, 'Aklan'),
    (5, 'Albay'),
    (6, 'Antique'),
    (7, 'Apayao'),
    (8, 'Aurora'),
    (9, 'Bacolod City'),
    (10, 'Basilan'),
    (11, 'Bataan'),
    (12, 'Batanes'),
    (13, 'Batangas'),
    (14, 'Benguet'),
    (15, 'Biliran'),
    (16, 'Bohol'),
    (17, 'Bukidnon'),
    (18, 'Bulacan'),
    (19, 'Cagayan'),
    (20, 'Camarines Norte'),
    (21, 'Camarines Sur'),
    (22, 'Camiguin'),
    (23, 'Capiz'),
    (24, 'Catanduanes'),
    (25, 'Cavite'),
    (26, 'Cebu'),
    (27, 'City of Isabela'),
    (28, 'City of Manila'),
    (29, 'Cotabato (North Cotabato)'),
    (30, 'Cotabato City'),
    (31, 'Davao City'),
    (32, 'Davao de Oro'),
    (33, 'Davao del Norte'),
    (34, 'Davao del Sur'),
    (35, 'Davao Occidental'),
    (36, 'Davao Oriental'),
    (37, 'Dinagat Islands'),
    (38, 'Eastern Samar'),
    (39, 'General Santos City'),
    (40, 'Guimaras'),
    (41, 'Ifugao'),
    (42, 'Ilocos Norte'),
    (43, 'Ilocos Sur'),
    (44, 'Iloilo'),
    (45, 'Isabela'),
    (46, 'Kalinga'),
    (47, 'La Union'),
    (48, 'Laguna'),
    (49, 'Lanao del Norte'),
    (50, 'Lanao del Sur'),
    (51, 'Leyte'),
    (52, 'Maguindanao'),
    (53, 'Marinduque'),
    (54, 'Masbate'),
    (55, 'Misamis Occidental'),
    (56, 'Misamis Oriental'),
    (57, 'Mountain Province'),
    (58, 'NCR, City of Manila, First District'),
    (59, 'NCR, Fourth District'),
    (60, 'NCR, Second District'),
    (61, 'NCR, Third District'),
    (62, 'Negros Occidental'),
    (63, 'Negros Oriental'),
    (64, 'Northern Samar'),
    (65, 'Nueva Ecija'),
    (66, 'Nueva Vizcaya'),
    (67, 'Occidental Mindoro'),
    (68, 'Oriental Mindoro'),
    (69, 'Palawan'),
    (70, 'Pampanga'),
    (71, 'Pangasinan'),
    (72, 'Quezon'),
    (73, 'Quirino'),
    (74, 'Rizal'),
    (75, 'Romblon'),
    (76, 'Samar (Western Samar)'),
    (77, 'Sarangani'),
    (78, 'Siquijor'),
    (79, 'Sorsogon'),
    (80, 'South Cotabato'),
    (81, 'Southern Leyte'),
    (82, 'Sultan Kudarat'),
    (83, 'Sulu'),
    (84, 'Surigao del Norte'),
    (85, 'Surigao del Sur'),
    (86, 'Tarlac'),
    (87, 'Tawi-Tawi'),
    (88, 'Zambales'),
    (89, 'Zamboanga del Norte'),
    (90, 'Zamboanga del Sur'),
    (91, 'Zamboanga Sibugay');

-- Disable identity insert
SET IDENTITY_INSERT Province OFF;
